# Generated by Django 4.1.5 on 2023-01-25 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z].*', 'Your name must start with a capital letter!')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z].*', 'Your name must start with a capital letter!')])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
